In [2]:
import time
import numpy as np

In [2]:
a=np.array([1,2,3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

# Fast Computation of NumPy array

In [20]:
x=np.random.randint(1,1000,10000000)

In [18]:
start=time.time()

a=sum(x)/len(x)

print('The mean of random numbers is', a )
print('The timetaken is', time.time()-start)

The mean of random numbers is 500.7233
The timetaken is 0.007005453109741211


In [19]:
start=time.time()

#b=np.mean(x)
b=np.average(x)



print('The mean of random numbers is', b)
print('The timetaken is', time.time()-start)



The mean of random numbers is 500.7233
The timetaken is 0.0019762516021728516


# Comparing Memory use

In [57]:
import numpy as np
import time 
import sys

# Creating a NumPy array with 100 elements
array = np.arange(100)
# array.itemsize : Size of one element
# array.size : length of array
print("Size of NumPy array: ", array.size * array.itemsize)

# Creating a list with 100 elements
# Now I'll print the size of list
list = range(0, 100)
# Multiplying size of 1 element with length of the list
print("Size of list: ", sys.getsizeof(1)*len(list))

Size of NumPy array:  400
Size of list:  2800


## Creating numpy arrays

_There are several ways to create ndarrays in NumPy. Will see two ways to create ndarrays_                                        

_1. Using regular Python lists_

_2.Using built-in NumPy functions_

In [85]:
# 1. Using regular Python lists


# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)


x =  [1 2 3 4 5]


In [86]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [89]:
# We save x into the current directory as 

np.save('my_array', x)


In [90]:
# We load the saved array from our current directory into variable y

y = np.load('my_array.npy')

# We print y
print(Y)

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [143]:
# Multiple ways to create numpy arrays using built in functions
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,3))

Z = np.arange(10)

print(X)
print(Z)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [88]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print(Y)

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


## Accessing elements in 1D Numpy Array - Indexing



In [26]:
np.array([1,2,3])

array([1, 2, 3])

In [48]:
countries=np.array(['India','US','UK','Canada','Aus','Middle East'])

# Let's access some elements with indices
print('This is First Element in countries:', countries[0]) 
print('This is Second Element in countries:', countries[1])
print('This is all Elements from fourth position in countries:', countries[4:])
print()


This is First Element in countries: India
This is Second Element in countries: US
This is all Elements from fourth position in countries: ['Aus' 'Middle East']



## Accessing elements in 2D Numpy Array - Indexing



In [29]:
countries_1=np.array([['India','US','UK'],['Canada','Aus','Middle East']])

# Let's access some elements with indices
print('This is First Element in countries:', countries_1[0]) 
print('This is Second Element in countries:', countries_1[1])
print('This is all Elements from fourth position in countries:', countries_1[1][1])

#There is one more way of accessing 2D arrays


This is First Element in countries: ['India' 'US' 'UK']
This is Second Element in countries: ['Canada' 'Aus' 'Middle East']
This is all Elements from fourth position in countries: Aus


In [22]:
countries_1

array([['India', 'US', 'UK'],
       ['Canada', 'Aus', 'Middle East']], dtype='<U11')

In [20]:
countries_1[1,1]

'Aus'

## Modifying elements in Array



In [191]:
print(countries_1)
countries_1[1,1]='England'

[['India' 'US' 'UK']
 ['Canada' 'England' 'Middle East']]


In [15]:
print(countries_1)
countries_1[1][1]='Eng'

[['India' 'US' 'UK']
 ['Canada' 'England' 'Middle East']]


In [36]:
countries_1

array([['India', 'US', 'UK'],
       ['1', '2', '3']], dtype='<U11')

## Deleting elements in Array



In [50]:
countries_1

array([['India', 'US', 'UK'],
       ['Canada', 'Aus', 'Middle East']], dtype='<U11')

In [27]:
a=np.array([1,2,3])
b=np.array([True,False,True])

In [28]:
a[b]

array([1, 3])

In [52]:
countries_1[0][1]

'US'

In [53]:
np.delete(countries_1, [0], axis=0)

array([['Canada', 'Aus', 'Middle East']], dtype='<U11')

## Adding elements in Array



In [61]:
countries_1

array([['India', 'US', 'UK'],
       ['Canada', 'Aus', 'Middle East']], dtype='<U11')

In [62]:
np.append(countries_1, [['Iran','Iraq','Japan']], axis=0)

array([['India', 'US', 'UK'],
       ['Canada', 'Aus', 'Middle East'],
       ['Iran', 'Iraq', 'Japan']], dtype='<U11')

In [32]:
countries_1

array([['India', 'US', 'UK'],
       ['Canada', 'Aus', 'Middle East']], dtype='<U11')

In [31]:
np.append(countries_1, [['Iran','Iraq','Japan']], axis=0)

array([['India', 'US', 'UK'],
       ['Canada', 'Aus', 'Middle East'],
       ['Iran', 'Iraq', 'Japan']], dtype='<U11')

In [25]:
countries_1

array([['India', 'US', 'UK'],
       ['Canada', 'Aus', 'Middle East']], dtype='<U11')

## Boolean operations



In [38]:
experience = np.array([10,7,15,8,9,6,12,4])
experience

array([10,  7, 15,  8,  9,  6, 12,  4])

In [39]:
experience > 10

array([False, False,  True, False, False, False,  True, False])

In [37]:
experience[experience > 10]

array([15, 12])

In [228]:
#np.insert(countries_1,1,[['A','B','C']],axis=0)

#Boolean Indexing, Set Operations, and Sorting

Vistara_card_holder=np.array(['Sam','Karthik','Arun','Arjun','Neha'])
Amex_card_holder=np.array(['Rohit','Arjun','Mayank','Sarthak','Neha'])


print('The people who hold both cards are :', np.intersect1d(Vistara_card_holder,Amex_card_holder))
print('The people who hold only Vistara card are:', np.setdiff1d(Vistara_card_holder,Amex_card_holder))





np.sort(Vistara_card_holder)

## Numpy Exercise 1

_**Let there be 2 arrays which hold the country and employee count info. Find the country which has maximum employee count**
_

In [34]:
countries=np.array(['India','US','UK','Canada','Aus','Middle East'])

In [35]:
employee_count = np.array([50000,25000,70000,5000,10000,1000])

## Numpy Exercise 2

**Let there be 2 arrays which hold the employees time in office information and employee_id in 2 separate arrays. Find the employee ids whose time in office is less than the average office hours of employees**

In [49]:
# time_in_office of employees

time_in_office=np.array([8,6.5,5.5,8,9,7.5,5,8.5,6.5,7,6.5,10.2,12,8.5,10.5,9.5,7,6,5.5])

In [40]:
# Employee ids (The order of both the arrays is same)
employee_id=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19])

## Numpy Exercise 3

**Find the count of employee whose time in office is >= 9 hrs**

In [152]:
# No of employees whose time_in_office is >=9 hrs 

time_in_office=np.array([8,6.5,5.5,8,9,7.5,5,8.5,6.5,7,6.5,10.2,12,8.5,10.5,9.5,7,6,5.5])